spring:
  main:
    web-application-type: none
    banner-mode: "off"

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  ai:
    mcp:
      server:
        stdio: true
        name: rex-mcp-lab-stdio
        version: 0.0.1
        type: SYNC

logging:
  level:
    root: INFO
